CREATE TABLE [dbo].[Scrim] (
    [Id]       INT  NOT NULL IDENTITY(1,1),
    [Team1]    UNIQUEIDENTIFIER  NULL,
    [Team2]    UNIQUEIDENTIFIER  NULL,
    [Datetime] DATETIME NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

