CREATE TABLE [dbo].[User]
(
    [Id] int NOT NULL PRIMARY KEY IDENTITY(1,1),
	[EmailAddress] NVARCHAR(MAX) NOT NULL, 
    [Username] NVARCHAR(MAX) NOT NULL, 
    [Password] NVARCHAR(MAX) NOT NULL, 
    [Role] NVARCHAR(MAX) NOT NULL DEFAULT 'Basic', 
    [DiscordUserId] NUMERIC(20) NOT NULL DEFAULT 00000000000000000000, 
    [Token] NVARCHAR(MAX) NOT NULL DEFAULT 'NoToken' 
)
